# _config.yml

# Título del sitio
title: "Mi Documentación"

# Menú de navegación lateral
just_the_docs:
  show_sidebar: true  # Habilita el menú lateral
  aux_links:  # Puedes agregar enlaces externos si lo deseas
    "GitHub Repo": 
      - https://github.com/TU-USUARIO/NOMBRE-DEL-REPOSITORIO

# Navegación
nav:
  - Home: index.md
  - Introducción: docs/intro.md
  - Guía rápida: docs/guia-rapida.md
