title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
#remote_theme: just-the-docs/just-the-docs
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  important:
    title: Key result
    color: green
  highlight:
    color: yellow
  core:
    color: purple
  fact:
    title: Key fact
    color: blue
  assumption:
    title: Key assumption
    color: yellow
  # Configuración de navegación
just_the_docs:
  show_nav: true
  show_toc: true  
baseurl: "/prueba"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
