title: Prueba
baseurl: "/prueba" # the subpath of your site, e.g. /blog
remote_theme: just-the-docs/just-the-docs

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  important:
    title: Key result
    color: green
  highlight:
    color: yellow
  core:
    color: purple
  fact:
    title: Key fact
    color: blue
  assumption:
    title: Key assumption
    color: yellow
